CustomersOrderOtomation/Controllers/AdminController.cs
using AutoMapper;
using CustomersOrderOtomation.Data.Models;
using CustomersOrderOtomation.Service.Abstract;
using CustomersOrderOtomation.ViewModel.ShopList;
using Microsoft.AspNetCore.Mvc;

namespace CustomersOrderOtomation.Controllers
{
    public class AdminController : Controller
    {
        private readonly IMapper mapper;

        public IShopListService ShopListService { get; }

        public AdminController(IShopListService shopListService, IMapper mapper) 
        {
            ShopListService = shopListService;
            this.mapper = mapper;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public List<ShopListViewModel> GetShopLists(int page = 1, int pageSize = 10) 
        {
           var dataList = ShopListService.GetAllShopListsWithSignalR().Skip((page -1)*pageSize).Take(pageSize).ToList();
          
            return dataList;
        }

        public IActionResult AdminProduct()
        {
            return View();
        }

        [HttpPost]
        public async Task<bool> UpdateShopListIsCompleteTrue(int orderNumber) 
        {
            try
            {
                var shop = await ShopListService.GetSingleShopListByIdAsyncPure(orderNumber);

                if (shop != null)
                {
                    ShopListService.CheckIsCompleteColumnForShopList(shop);
                }

                return true;
            }
            catch (Exception ex)
            {
                return false;
            }



           
        }
    }
}

CustomersOrderOtomation/Controllers/CategoryController.cs
using CustomersOrderOtomation.Service.Abstract;
using CustomersOrderOtomation.ViewModel.Category;
using Microsoft.AspNetCore.Mvc;

namespace CustomersOrderOtomation.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryService categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            this.categoryService = categoryService;
        }
        public async Task<List<CategoryViewModel>> GetCategories()
        {
            return await categoryService.GetAllCategories();
        }
    }
}

CustomersOrderOtomation/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;

namespace CustomersOrderOtomation.Controllers
{
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

CustomersOrderOtomation/Controllers/FileController.cs
using CustomersOrderOtomation.Service.Concrete;
using Microsoft.AspNetCore.Mvc;

namespace CustomersOrderOtomation.Controllers
{
    public class FileController : Controller
    {
        private readonly StorageService _storageService;

        public FileController(StorageService storageService)
        {
            _storageService = storageService;
        }

        [HttpPost("upload")]
        public async Task<IActionResult> Upload(IFormFile file)
        {
            if (file == null || file.Length == 0)
                return BadRequest("No file uploaded");

            try
            {
                var fileUrl = await _storageService.UploadFileAsync(file);
                return Ok(new { fileUrl });
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"Upload failed: {ex.Message}");
            }
        }
    }
}

CustomersOrderOtomation/Controllers/ManagementController.cs
using CustomersOrderOtomation.Service.Abstract;
using CustomersOrderOtomation.ViewModel.Category;
using CustomersOrderOtomation.ViewModel.Product;
using CustomersOrderOtomation.ViewModel.ShopList;
using Microsoft.AspNetCore.Mvc;

namespace CustomersOrderOtomation.Controllers
{
    public class ManagementController : Controller
    {
        public ManagementController()
        {

        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> ManageProduct([FromServices] IManagemenetService managementService)
        {
            var products = await managementService.GetAllProductsForManagement();

            return View(products);
        }

        public async Task<IActionResult> ManageCategory([FromServices] IManagemenetService managementService)
        {
            var categories = await managementService.GetAllCategoriesForManagement();

            return View(categories);
        }

        [HttpGet]
        public async Task<List<ShopListViewModel>> GetShopLists([FromServices] IShopListService shopListService, int page = 1, int pageSize = 10)
        {
            return await shopListService.GetShopLists(page, pageSize);
        }


        [HttpPost]
        public async Task<bool> UpdateShopListIsCompleteTrue([FromServices] IShopListService shopListService, int orderNumber)
        {
            return await shopListService.UpdateShopListIsCompleteTrue(orderNumber);
        }

        [HttpPost]
        public async Task<bool> CreateOrUpdateProduct(IFormCollection parameters, [FromServices] IManagemenetService managementService)
        {
            return await managementService.CreateOrUpdateProductAsyncManagement(parameters); 
        }

        public async Task<ProductViewModelManagement> GetSingleProductByIdForManagement([FromServices] IManagemenetService managementService, int productId)
        {
            var product = await managementService.GetSingleProductByIdForManagement(productId);

            return product;
        }

        [HttpGet]
        public async Task<List<ProductViewModelManagement>> GetAllProducts([FromServices] IManagemenetService managementService)
        {
            var products = await managementService.GetAllProductsForManagement();

            return products;
        }

        public async Task<CategoryViewModelManagement> GetSingleCategoryByIdForManagement([FromServices] IManagemenetService managementService, int categoryId)
        {
            var product = await managementService.GetSingleCategoryByIdForManagement(categoryId);

            return product;
        }

        [HttpPost]
        public async Task<bool> CreateOrUpdateCategory(IFormCollection parameters, [FromServices] IManagemenetService managementService)
        {
            return await managementService.CreateOrUpdateCategoryAsyncManagement(parameters);
        }

        public async Task<List<CategoryViewModelManagement>> GetAllCategories([FromServices] IManagemenetService managementService)
        {
            var categories = await managementService.GetAllCategoriesForManagement();

            return categories;
        }
    }
}

CustomersOrderOtomation/Controllers/ProductController.cs
using CustomersOrderOtomation.Service.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace CustomersOrderOtomation.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService productService;

        public ProductController(IProductService productService)
        {
            this.productService = productService;
        }

        public async Task<IActionResult> Shop()
        {
            var products = await productService.GetAllProducts();
            return View(products);
        }

        public async Task<IActionResult> ShopDetailed(int productId)
        {
            var produt = await productService.GetSingleProductByIdAsync(productId);
            return View(produt);
        }



        public async Task<IActionResult> GetProductsByCategory(int categoryId)
        {
            var products = await productService.GetProductsByCategory(categoryId);

            return View("Shop", products);
        }
    }
}

CustomersOrderOtomation/Controllers/ShopController.cs
using CustomersOrderOtomation.Dto.Dtos;
using CustomersOrderOtomation.Service.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace CustomersOrderOtomation.Controllers
{
    public class ShopController : Controller
    {
        public ShopController()
        {
        }

        public IActionResult ShoppingCard()
        {
            return View();
        }

        [HttpPost]
        public async Task<List<ProductForGetShopListDto>> GetShoppingCardProducts([FromServices] IProductService productService, [FromBody] List<ProductForAddShopListDto> prod)
        {
            return await productService.GetShoppingCardProducts(prod);
        }

        public async Task<IActionResult> AddShoppingCardProductsToShopList([FromServices] IShopListService shopListService, string cusName, string cusTableNo, [FromBody] List<ShopListAddShoppingCardProductsDto> dto)
        {
            var durum = await shopListService.AddShoppingCardProductsToShopList(cusName, cusTableNo, dto);
            return durum == true ? Json("basarili") : StatusCode(500, "Hata olustu");
        }
    }
}

CustomersOrderOtomation/Views/Admin/AdminProduct.cshtml
@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


<table class="table align-middle mb-0 bg-white">
    <thead class="bg-light">
        <tr>
            <th>Name</th>
            <th>Title</th>
            <th>Status</th>
            <th>Position</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                <div class="d-flex align-items-center">
                    <img src="https://mdbootstrap.com/img/new/avatars/8.jpg"
                         alt=""
                         style="width: 45px; height: 45px"
                         class="rounded-circle" />
                    <div class="ms-3">
                        <p class="fw-bold mb-1">John Doe</p>
                        <p class="text-muted mb-0">john.doe@gmail.com</p>
                    </div>
                </div>
            </td>
            <td>
                <p class="fw-normal mb-1">Software engineer</p>
                <p class="text-muted mb-0">IT department</p>
            </td>
            <td>
                <span class="badge badge-success rounded-pill d-inline">Active</span>
            </td>
            <td>Senior</td>
            <td>
                <button type="button" class="btn btn-link btn-sm btn-rounded">
                    Edit
                </button>
            </td>
        </tr>
        <tr>
            <td>
                <div class="d-flex align-items-center">
                    <img src="https://mdbootstrap.com/img/new/avatars/6.jpg"
                         class="rounded-circle"
                         alt=""
                         style="width: 45px; height: 45px" />
                    <div class="ms-3">
                        <p class="fw-bold mb-1">Alex Ray</p>
                        <p class="text-muted mb-0">alex.ray@gmail.com</p>
                    </div>
                </div>
            </td>
            <td>
                <p class="fw-normal mb-1">Consultant</p>
                <p class="text-muted mb-0">Finance</p>
            </td>
            <td>
                <span class="badge badge-primary rounded-pill d-inline">Onboarding</span>
            </td>
            <td>Junior</td>
            <td>
                <button type="button"
                        class="btn btn-link btn-rounded btn-sm fw-bold"
                        data-mdb-ripple-color="dark">
                    Edit
                </button>
            </td>
        </tr>
        <tr>
            <td>
                <div class="d-flex align-items-center">
                    <img src="https://mdbootstrap.com/img/new/avatars/7.jpg"
                         class="rounded-circle"
                         alt=""
                         style="width: 45px; height: 45px" />
                    <div class="ms-3">
                        <p class="fw-bold mb-1">Kate Hunington</p>
                        <p class="text-muted mb-0">kate.hunington@gmail.com</p>
                    </div>
                </div>
            </td>
            <td>
                <p class="fw-normal mb-1">Designer</p>
                <p class="text-muted mb-0">UI/UX</p>
            </td>
            <td>
                <span class="badge badge-warning rounded-pill d-inline">Awaiting</span>
            </td>
            <td>Senior</td>
            <td>
                <button type="button"
                        class="btn btn-link btn-rounded btn-sm fw-bold"
                        data-mdb-ripple-color="dark">
                    Edit
                </button>
            </td>
        </tr>
    </tbody>
</table>

CustomersOrderOtomation/Views/Dashboard/Index.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Shoppers &mdash; Colorlib e-Commerce Template</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>
<body>

    <div class="site-wrap">

        <div class="site-blocks-cover" style="background-image: url(images/hero_1.jpg);" data-aos="fade">
            <div class="container">
                <div class="row align-items-start align-items-md-center justify-content-end">
                    <div class="col-md-5 text-center text-md-left pt-5 pt-md-0">
                        <h1 class="mb-2">Finding Your Perfect Shoes</h1>
                        <div class="intro-text text-center text-md-left">
                            <p class="mb-4">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus at iaculis quam. Integer accumsan tincidunt fringilla. </p>
                            <p>
                                <a href="#" class="btn btn-sm btn-primary">Shop Now</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="site-section site-section-sm site-blocks-1">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 col-lg-4 d-lg-flex mb-4 mb-lg-0 pl-4" data-aos="fade-up" data-aos-delay="">
                        <div class="icon mr-4 align-self-start">
                            <span class="icon-truck"></span>
                        </div>
                        <div class="text">
                            <h2 class="text-uppercase">Free Shipping</h2>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus at iaculis quam. Integer accumsan tincidunt fringilla.</p>
                        </div>
                    </div>
                    <div class="col-md-6 col-lg-4 d-lg-flex mb-4 mb-lg-0 pl-4" data-aos="fade-up" data-aos-delay="100">
                        <div class="icon mr-4 align-self-start">
                            <span class="icon-refresh2"></span>
                        </div>
                        <div class="text">
                            <h2 class="text-uppercase">Free Returns</h2>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus at iaculis quam. Integer accumsan tincidunt fringilla.</p>
                        </div>
                    </div>
                    <div class="col-md-6 col-lg-4 d-lg-flex mb-4 mb-lg-0 pl-4" data-aos="fade-up" data-aos-delay="200">
                        <div class="icon mr-4 align-self-start">
                            <span class="icon-help"></span>
                        </div>
                        <div class="text">
                            <h2 class="text-uppercase">Customer Support</h2>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus at iaculis quam. Integer accumsan tincidunt fringilla.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="site-section site-blocks-2">
            <div class="container">
                <div class="row">

                    @for(int i = 0; i < 3; i++)
                    {
                        <div class="col-sm-6 col-md-6 col-lg-4 mb-4 mb-lg-0" data-aos="fade" data-aos-delay="">
                            <a class="block-2-item" href="#">
                                <figure class="image">
                                    <img src="~/images/women.jpg" alt="" class="img-fluid">
                                </figure>
                                <div class="text">
                                    <span class="text-uppercase">Collections</span>
                                    <h3>Women</h3>
                                </div>
                            </a>
                        </div>
                    }
                   
                </div>
            </div>
        </div>

        <div class="site-section block-3 site-blocks-2 bg-light">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-7 site-section-heading text-center pt-4">
                        <h2>Featured Products</h2>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="nonloop-block-3 owl-carousel">

                            @for(int i = 0; i < 5; i++)
                            {
                                <div class="item">
                                    <div class="block-4 text-center">
                                        <figure class="block-4-image">
                                            <img src="~/images/cloth_1.jpg" alt="Image placeholder" class="img-fluid">
                                        </figure>
                                        <div class="block-4-text p-4">
                                            <h3><a href="#">Tank Top</a></h3>
                                            <p class="mb-0">Finding perfect t-shirt</p>
                                            <p class="text-primary font-weight-bold">$50</p>
                                        </div>
                                    </div>
                                </div>
                            }
                      
                    
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="site-section block-8">
            <div class="container">
                <div class="row justify-content-center  mb-5">
                    <div class="col-md-7 site-section-heading text-center pt-4">
                        <h2>Big Sale!</h2>
                    </div>
                </div>
                <div class="row align-items-center">
                    <div class="col-md-12 col-lg-7 mb-5">
                        <a href="#"><img src="~/images/blog_1.jpg" alt="Image placeholder" class="img-fluid rounded"></a>
                    </div>
                    <div class="col-md-12 col-lg-5 text-center pl-md-5">
                        <h2><a href="#">50% less in all items</a></h2>
                        <p class="post-meta mb-4">By <a href="#">Carl Smith</a> <span class="block-8-sep">&bullet;</span> September 3, 2018</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam iste dolor accusantium facere corporis ipsum animi deleniti fugiat. Ex, veniam?</p>
                        <p><a href="#" class="btn btn-primary btn-sm">Shop Now</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

CustomersOrderOtomation/Views/Product/Shop.cshtml
@model List<CustomersOrderOtomation.ViewModel.Product.ProductViewModel>

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Shoppers &mdash; Colorlib e-Commerce Template</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>
<body>

    <div class="site-wrap">
        <div class="bg-light py-3">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 mb-0"><a href="index.html">Home</a> <span class="mx-2 mb-0">/</span> <strong class="text-black">Shop</strong></div>
                </div>
            </div>
        </div>

        <div class="site-section">
            <div class="container">

                <div class="row mb-5">
                    <div class="col-md-9 order-2">

               
                        <div class="row mb-5">

                            @foreach(var item in Model)
                            {
                                <div class="col-sm-6 col-lg-4 mb-4" data-aos="fade-up">
                                    <div class="block-4 text-center border">
                                        <figure class="block-4-image">
                                            <a asp-controller="Product" asp-action="ShopDetailed" asp-route-productId="@item.Id"><img src="~/images/cloth_1.jpg" alt="Image placeholder" class="img-fluid"></a>
                                        </figure>
                                        <div class="block-4-text p-4">
                                            <h3><a href="shop-single.html">@item.Name</a></h3>
                                            <p class="text-primary font-weight-bold">@item.Price TL</p>
                                        </div>
                                    </div>
                                </div>
                            }

                    
                      

                        </div>
                        <div class="row" data-aos="fade-up">
                            <div class="col-md-12 text-center">
                                <div class="site-block-27">
                                    <ul>
                                        <li><a href="#">&lt;</a></li>
                                        <li class="active"><span>1</span></li>
                                        <li><a href="#">2</a></li>
                                        <li><a href="#">3</a></li>
                                        <li><a href="#">4</a></li>
                                        <li><a href="#">5</a></li>
                                        <li><a href="#">&gt;</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-3 order-1 mb-5 mb-md-0">
                        <div class="border p-4 rounded mb-4">
                            <h3 class="mb-3 h6 text-uppercase text-black d-block">Categories</h3>
                            <ul class="list-unstyled mb-0" id="ulCategorListField">
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
</body>
</html>

<script type="text/javascript">
    $(document).ready(function () {
        getCategoriesForShopPage();
    });


</script>

CustomersOrderOtomation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CustomersOrderOtomation</title>
    <link rel="stylesheet" href="~/css/main.min.css">
</head>
<body>
    <header class="site-navbar" role="banner">
        <div class="site-navbar-top">
            <div class="container">
                <div class="row align-items-center">

                    <div class="col-6 col-md-4 order-2 order-md-1 site-search-icon text-left">
                    </div>

                    <div class="col-12 mb-3 mb-md-0 col-md-4 order-1 order-md-2 text-center">
                        <div class="site-logo">
                            <a asp-controller="Dashboard" asp-action="Index" class="js-logo-clone">Shoppers</a>
                        </div>
                    </div>

                    <div class="col-6 col-md-4 order-3 order-md-3 text-right">
                        <div class="site-top-icons">
                            <ul>
                                <li>
                                    <a asp-controller="Shop" asp-action="ShoppingCard" class="site-cart">
                                        <span class="icon icon-shopping_cart"></span>
                                        <span class="count" id="spnShopListProductCount"></span>
                                    </a>
                                </li>
                                <li class="d-inline-block d-md-none ml-md-0"><a href="#" class="site-menu-toggle js-menu-toggle"><span class="icon-menu"></span></a></li>
                            </ul>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <nav class="site-navigation text-right text-md-center" role="navigation">
            <div class="container">
                <ul class="site-menu js-clone-nav d-none d-md-block">
                    <li>
                        <a asp-controller="Dashboard" asp-action="Index">Dashboard</a>
                    </li>

                    <li>
                        <a asp-controller="Product" asp-action="Shop">Shop</a>
                    </li>

                </ul>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="site-footer border-top">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 mb-5 mb-lg-0">
                    <div class="row">
                        <div class="col-md-12">
                            <h3 class="footer-heading mb-4">Navigations</h3>
                        </div>
                        <div class="col-md-6 col-lg-4">
                            <ul class="list-unstyled">
                                <li><a href="#">Sell online</a></li>
                                <li><a href="#">Features</a></li>
                                <li><a href="#">Shopping cart</a></li>
                                <li><a href="#">Store builder</a></li>
                            </ul>
                        </div>
                        <div class="col-md-6 col-lg-4">
                            <ul class="list-unstyled">
                                <li><a href="#">Mobile commerce</a></li>
                                <li><a href="#">Dropshipping</a></li>
                                <li><a href="#">Website development</a></li>
                            </ul>
                        </div>
                        <div class="col-md-6 col-lg-4">
                            <ul class="list-unstyled">
                                <li><a href="#">Point of sale</a></li>
                                <li><a href="#">Hardware</a></li>
                                <li><a href="#">Software</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-3 mb-4 mb-lg-0">
                    <h3 class="footer-heading mb-4">Promo</h3>
                    <a href="#" class="block-6">
                        <img src="~/images/hero_1.jpg" alt="Image placeholder" class="img-fluid rounded mb-4">
                        <h3 class="font-weight-light  mb-0">Finding Your Perfect Shoes</h3>
                        <p>Promo from  nuary 15 &mdash; 25, 2019</p>
                    </a>
                </div>
                <div class="col-md-6 col-lg-3">
                    <div class="block-5 mb-5">
                        <h3 class="footer-heading mb-4">Contact Info</h3>
                        <ul class="list-unstyled">
                            <li class="address">203 Fake St. Mountain View, San Francisco, California, USA</li>
                            <li class="phone"><a href="tel://23923929210">+2 392 3929 210</a></li>
                            <li class="email">emailaddress@domain.com</li>
                        </ul>
                    </div>

                    <div class="block-7">
                        <form action="#" method="post">
                            <label for="email_subscribe" class="footer-heading">Subscribe</label>
                            <div class="form-group">
                                <input type="text" class="form-control py-4" id="email_subscribe" placeholder="Email">
                                <input type="submit" class="btn btn-sm btn-primary" value="Send">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </footer>

    <script src="~/js/base.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

<script type="text/javascript">

    $(document).ready(function () {
        let basket =JSON.parse(localStorage.getItem("productsBasket"));
        const sum = basket.reduce((acc, current) => acc + parseInt(current.piece), 0);
        $("#spnShopListProductCount").text(sum);

    });

</script>

CustomersOrderOtomation/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Dashboard</title>
    <link rel="stylesheet" href="~/css/main.min.css">


    <!-- Custom styles for this template-->
</head>
<body>
    <div class="row">
        <div class="col-md-2">
            <div class="d-flex flex-column flex-shrink-0 p-3 bg-light" style="width: 280px;">
                <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
                    <span class="fs-4">Admin Paneli</span>
                </a>
                <hr>
                <ul class="nav nav-pills flex-column mb-auto">
                    <li class="nav-item">
                        <a asp-controller="Management" asp-action="Index" class="nav-link link-dark">Orders</a>
                    </li>
                    <li>
                        <a asp-controller="Management" asp-action="ManageCategory" class="nav-link link-dark">Categories</a>
                    </li>
                    <li>
                        <a asp-controller="Management" asp-action="ManageProduct" class="nav-link link-dark">Products</a>
                    </li>
                    <li>
                        <a href="#" class="nav-link link-dark">
                            Customers
                        </a>
                    </li>
                </ul>

            </div>
        </div>
        <div class="col-md-10">
            @RenderBody()
        </div>

    </div>

    <script src="~/js/base.js"></script>
    <script src="~/lib/signalr/signalr.js"></script>
    <script src="https://kit.fontawesome.com/95caf2660a.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>